name: GitHub Actions Auto Run

on:
  workflow_dispatch:
  schedule:
    - cron: '30 23 * * *'   #在每天23:30（UTC时间）即7：30（BTC）自动运行

jobs:
  bot:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - name: Set up Python
      uses: actions/setup-python@v1
    - name: Install requirements
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
    - name: AutoRun
      env:  
        ZXC: 0    #0为不推送，1为企业微信应用消息推送，2为Server酱推送
        IMEICODE: ${{ secrets.IMEICODE }}
        SCKEY: ${{ secrets.SCKEY }}
        CORPID: ${{ secrets.CORPID }}
        SECRET: ${{ secrets.SECRET }}
        AGENTID: ${{ secrets.AGENTID }}
      run: python PyAipao.py
